---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: interop-be-signalhub-registry-updater-es-cronjob
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: interop-be-signalhub-registry-updater-es-cronjob
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.cronjobs.registryUpdaterSchedule }}
  suspend: true
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          {{- if .Values.imagePullSecret }}
          imagePullSecrets:
            - name: {{ .Values.imagePullSecret }}
          {{- end }}
          automountServiceAccountToken: false
          serviceAccountName: {{ .Values.serviceAccount.name }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
          - name: interop-be-registry-updater-es-ms
            securityContext:
              {{- toYaml .Values.securityContext | nindent 12 }}
            image: "{{ .Values.image.repository }}/interop-be-signalhub-registry-updater:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            {{- with .Values.env }}
            env:
              {{- range $key, $val := . }}
              - name: {{ $key }}
                value: {{ $val | quote }}
              {{- end }}
            {{- end }}
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
            args: ["--application.type=ESERVICE"]
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: interop-be-signalhub-registry-updater-ag-cronjob
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: interop-be-signalhub-registry-updater-ag-cronjob
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.cronjobs.registryUpdaterSchedule }}
  suspend: true
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          {{- if .Values.imagePullSecret }}
          imagePullSecrets:
            - name: {{ .Values.imagePullSecret }}
          {{- end }}
          automountServiceAccountToken: false
          serviceAccountName: {{ .Values.serviceAccount.name }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
          - name: interop-be-registry-updater-ag-ms
            securityContext:
              {{- toYaml .Values.securityContext | nindent 12 }}
            image: "{{ .Values.image.repository }}/interop-be-signalhub-registry-updater:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            {{- with .Values.env }}
            env:
              {{- range $key, $val := . }}
              - name: {{ $key }}
                value: {{ $val | quote }}
              {{- end }}
            {{- end }}
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
            args: ["--application.type=AGREEMENT"]
          restartPolicy: Never

