---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interop-be-signalhub-push-service-deployment
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: interop-be-signalhub-push-service-ms
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: interop-be-signalhub-push-service-ms
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: interop-be-signalhub-push-service-ms
    spec:
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- end }}
      automountServiceAccountToken: false
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: interop-be-signalhub-push-service-ms
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/interop-be-signalhub-push-service:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: main
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.pushLivenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.pushReadinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.env }}
          env:
            {{- range $key, $val := . }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            - name: SPRING_WEBFLUX_BASEPATH
              value: /push
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: interop-be-signalhub-push-service-service
spec:
  ports:
    - port: {{ .Values.image.port }}
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: interop-be-signalhub-push-service-ms
